task distZip2(type: Zip) {
    dependsOn tasks.jar
    from(configurations.runtimeClasspath) {
        into('lib')
    }
    from(tasks.jar)
    from('dist') {
        include '*.bat'
        include '*.sh'
        filePermissions {
            unix(0755)
        }
    }
    archiveFileName = base.archivesName.get() + '-' + project.version + '.zip'
    destinationDirectory = layout.buildDirectory.dir('distributions')
}

assemble.dependsOn 'distZip2'

jlink {
    options = ['--strip-debug', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'jtrrntzip'
    }
    jpackage {
        skipInstaller = true
        imageName = 'Jtrrntzip'
        if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
            imageOptions = ['--win-console']
        }
    }
}
