publishing {
    repositories {
        maven {
            name = "jtrrntzip"
            url = uri("https://maven.pkg.github.com/optyfr-org/Jtrrntzip")
            credentials {
                username = providers.gradleProperty("gpr.user").orElse(providers.environmentVariable("USERNAME")).getOrNull()
                password = providers.gradleProperty("gpr.key").orElse(providers.environmentVariable("TOKEN")).getOrNull()
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            artifactId = "jtrrntzip"
            from(components.java)
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'JTrrntzip'
                description = 'Java version of trrntzip Based on C# code from TrrntzipDN by GordonJ'
                url = 'https://github.com/optyfr-org/Jtrrntzip'
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://raw.githubusercontent.com/optyfr-org/Jtrrntzip/master/LICENSE'
                    }
                }
                developers {
                    developer {
                        id = 'optyfr'
                        name = 'optyfr'
                        email = '17027109+optyfr@users.noreply.github.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/optyfr-org/Jtrrntzip.git'
                    developerConnection = 'scm:git:git@github.com:optyfr-org/Jtrrntzip.git'
                    url = 'https://github.com/optyfr-org/Jtrrntzip.git'
                }
            }
        }
    }
}
