name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml

  test:
    needs: [build]
    uses: ./.github/workflows/ci-test.yml

  sonar:
    needs: [build, test]
    uses: ./.github/workflows/ci-sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
