name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  prepare:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Get tag version
        id: vars
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create GitHub release
        uses: optyfr-org/composite-actions/ensure-release@5d5db305592dd78357c2980b4482d9dc3b692311 # v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  library:
    needs: prepare
    uses: ./.github/workflows/release-library.yml
    with:
      release-version: ${{ needs.prepare.outputs.version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jpackage:
    needs: prepare
    uses: ./.github/workflows/release-jpackage.yml
    with:
      release-version: ${{ needs.prepare.outputs.version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  native:
    needs: prepare
    uses: ./.github/workflows/release-native.yml
    with:
      release-version: ${{ needs.prepare.outputs.version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
